version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: quartz-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: quartz_application
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d

  quartz-app:
    build: .
    container_name: quartz-scheduler
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/quartz_application?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: altynbek4649@gmail.com
      SPRING_MAIL_PASSWORD: mvly tgfn cwnf qifs
      SPRING_MAIL_PROPERTIES_MAIL_SMPT_AUTH: true
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: true
    restart: on-failure

volumes:
  mysql_data:
